/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UntitledRouteImport } from './routes/untitled'
import { Route as SnakeRouteImport } from './routes/snake'
import { Route as ReactionRouteImport } from './routes/reaction'
import { Route as MindHackerRouteImport } from './routes/mind-hacker'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const UntitledRoute = UntitledRouteImport.update({
  id: '/untitled',
  path: '/untitled',
  getParentRoute: () => rootRouteImport,
} as any)
const SnakeRoute = SnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionRoute = ReactionRouteImport.update({
  id: '/reaction',
  path: '/reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const MindHackerRoute = MindHackerRouteImport.update({
  id: '/mind-hacker',
  path: '/mind-hacker',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/memory': typeof MemoryRoute
  '/mind-hacker': typeof MindHackerRoute
  '/reaction': typeof ReactionRoute
  '/snake': typeof SnakeRoute
  '/untitled': typeof UntitledRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/memory': typeof MemoryRoute
  '/mind-hacker': typeof MindHackerRoute
  '/reaction': typeof ReactionRoute
  '/snake': typeof SnakeRoute
  '/untitled': typeof UntitledRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/memory': typeof MemoryRoute
  '/mind-hacker': typeof MindHackerRoute
  '/reaction': typeof ReactionRoute
  '/snake': typeof SnakeRoute
  '/untitled': typeof UntitledRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/games'
    | '/memory'
    | '/mind-hacker'
    | '/reaction'
    | '/snake'
    | '/untitled'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/games'
    | '/memory'
    | '/mind-hacker'
    | '/reaction'
    | '/snake'
    | '/untitled'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/games'
    | '/memory'
    | '/mind-hacker'
    | '/reaction'
    | '/snake'
    | '/untitled'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRoute
  MemoryRoute: typeof MemoryRoute
  MindHackerRoute: typeof MindHackerRoute
  ReactionRoute: typeof ReactionRoute
  SnakeRoute: typeof SnakeRoute
  UntitledRoute: typeof UntitledRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/untitled': {
      id: '/untitled'
      path: '/untitled'
      fullPath: '/untitled'
      preLoaderRoute: typeof UntitledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snake': {
      id: '/snake'
      path: '/snake'
      fullPath: '/snake'
      preLoaderRoute: typeof SnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reaction': {
      id: '/reaction'
      path: '/reaction'
      fullPath: '/reaction'
      preLoaderRoute: typeof ReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind-hacker': {
      id: '/mind-hacker'
      path: '/mind-hacker'
      fullPath: '/mind-hacker'
      preLoaderRoute: typeof MindHackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRoute,
  MemoryRoute: MemoryRoute,
  MindHackerRoute: MindHackerRoute,
  ReactionRoute: ReactionRoute,
  SnakeRoute: SnakeRoute,
  UntitledRoute: UntitledRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
